### ISSUE TITLE
Database maken

### ISSUE THREAD

**Issue by arjenpalland** [nielsbergwerff/Ratatosk#15]
Het [strokendiagram](https://docs.google.com/spreadsheets/d/19ChBSUV-GLhKGmyBxKOKV7ZUtEKDNA6lo9MOR-gjA4Q/edit?usp=sharing) is af.
De username van het testaccount is 'root' en het wachtwoord van is 'pass'. 
[Hier](https://docs.google.com/document/d/1wZ_SPMKiBZ1FoeV3KwolI-o5NBLKrnGgp4RnkNE_Ffo/edit?usp=sharing) vind je de database.

**Comment by StriderOfTheWest** [comment]
Suggestie: voeg toe: laatst gebruikte groep
