### ISSUE TITLE
Onderwerp bedenken

### ISSUE THREAD

**Issue by nielsbergwerff** [nielsbergwerff/Ratatosk#5]
**Uiteindelijke keuze:** Een chat applicatie: communicatie platform voor onze school. Met deze applicatie kunnen leerlingen en leraren contact met elkaar houden. Er worden automatisch groepen gevormd van mentorklassen en clusters. Verder kunnen er nog vrij  groepen aangemaakt worden. Wel is deze applicatie exclusief voor leerlingen, leraren en ander personeel van het Greijdanus.

**Comment by StriderOfTheWest** [comment]
Voorstel 1: Een chat applicatie voor Windows (voor school?)
 - Deze misschien ook online beschikbaar maken (is makkelijk vgm met Javascript)
Voorstel 2: Een Discord bot
