### ISSUE TITLE
Overleg met Greijdanus

### ISSUE THREAD

**Issue by StriderOfTheWest** [nielsbergwerff/Ratatosk#7]
We hebben met onze opdrachtgever (het Greijdanus) overlegd wat de precieze vereisten zijn door middel van enquêtes.
[De reacties van de leerlingen](https://docs.google.com/spreadsheets/d/1nQmR_XPLPr2jpHsTVJQdy1kXZJK2JgKRdBVk0K2Nm6E/edit#gid=1521884354)
[De reacties van de leraren](https://docs.google.com/spreadsheets/d/1YwHd5QG_PMJzstk4sFXMfCvnJpy97E7CJziR_uop7BY/edit#gid=2001306950)

 
_Hierdoor kunnen we het volgende zeggen:_

**Besturingssysteem/platform:** ChromeOS wordt buitenschool het meest gebruikt onder de leerlingen. Het was vanaf het begin al het idee om een browser applicatie te maken, maar dit versterkt dat nog even. Mensen die geen ChromeOS gebruiken, gebruiken in de eerste plek Windows. Daarna komt Android en daarna iOS. We zullen in deze volgorde ondersteuning voor de platformen verlenen.

**Kleurenschema:** De leerlingen zien het liefst de kleuren van het Greijdanus terug in de chat. Ook hebben ze liever een licht design dan een donker design, hoewel deze twee redelijk gelijk op gaan. Een kleurrijk ontwerp is niet erg geliefd. Wij gaan dan ook voor de Greijdanus-stijl, die van zichzelf al licht is.

**App:** 118 van de leerlingen zegt dat ze wel een mobiele app zouden willen installeren, tegenover 83 respondenten die zeggen dat niet te willen doen. Het maken van een Android en/of een IOS applicatie lijkt ons het dan ook waard. 

**Gebruiksvriendlijkheid vs. opties:** Aan de leraren hebben we op een schaal van 1 tot 5 gevraagd of ze de nadruk willen hebben op de gebruiksvriendelijkheid of op meer opties. Het resultaat was als volgt:

_Veel opties_
1 : 0
2 : 1
3 : 6
4 : 3
5 : 6
_Gebruiksvriendelijkheid_

De nadruk ligt dus op gebruiksvriendelijkheid.

**Controle door leraren:** De leraren zeggen dat ze het liefst de chat willen kunnen blokkeren tijdens de les. Ook zeggen 4/16 leraren dat ze alles willen kunnen lezen wat de leerling stuurt.  Maar 2/16 hoeft geen controle over de chat te hebben.

**In de realiteit brengen?** De leerlingen zijn over het algemeen positief over een Greijdanus-chat, met maar 44 van de 240 die zeggen dat ze de chat niet zouden gebruiken. De leraren zijn minder positief, ze vermelden onder andere dat er al genoeg andere manieren zijn om te communiceren, zoals Whatsapp en Natschool mail, en dat ze liever niet 24/7 bereikbaar willen zijn. Ook wordt erop gewezen dat fysiek contact beter is voor het leerproces dan met een online chat. 9 van de 15 leraren zou zo'n chat niet (willen) gebruiken. Hier moeten we dus wel rekening mee gaan houden. 

**Veel gevraagde functies:** De leerlingen zouden de chat gebruiken voor (op aflopend voorkomen):

1. Vragen aan docenten
2. Overleg met andere leerlingen
3. Mededelingen voor klassen en clusters
4. Gesprekken met de mentor

Bij leraren ziet de verdeling er als volgt uit:

1. Mededelingen voor klassen en clusters
2. Helpen van leerlingen
3. Overleg met andere leraren
4. Gesprekken met mentorleerlingen
5. Controleren van huiswerk

**Extra functies:** Suggesties van leerlingen: 

- [ ] roosters
- [ ] cijfers
- [ ] absenties bekijken
- [ ] (google) documenten en foto's dele
- [ ]  zoekfunctie naar leraren/leerlingen en contactgegevens weergeven
- [ ] meldingen bij berichten en roosterwijzigingen
- [ ] planning kunnen maken (voor toetsweek bijvoorbeeld)
- [ ] klassen/clusters bekijken
- [ ] tussenuur matcher (waarmee je kunt zien wie er nog meer tussenuur heeft
- [ ] huiswerkagenda
- [ ] van andere leerlingen en leraren de roosters kunnen bekijken
- [ ] (video)bellen
Ze zien dus het liefst de functies terug die al bestaan in andere applicaties van het Greijdanus. We zullen proberen zo veel mogelijk in onze applicatie terug te laten komen, maar al deze items zijn optioneel voor ons of alleen op langere termijn haalbaar.

**Comment by StriderOfTheWest** [comment]
(Hier)[https://docs.google.com/forms/d/1BAfe06ys-fSTkGDiNVFAtcSbiUhO0naHCUzCyZuglKM/edit?usp=sharing] is de link naar de google form.

**Comment by nielsbergwerff** [comment]
> We hebben met onze opdrachtgever (het Greijdanus) overlegd wat de precieze vereisten zijn door middel van enquêtes.
> [De reacties van de leerlingen](https://docs.google.com/spreadsheets/d/1nQmR_XPLPr2jpHsTVJQdy1kXZJK2JgKRdBVk0K2Nm6E/edit#gid=1521884354)
> [De reacties van de 

- leraren](https://docs.google.com/spreadsheets/d/1YwHd5QG_PMJzstk4sFXMfCvnJpy97E7CJziR_uop7BY/edit#gid=2001306950)

> 
> Hierdoor kunnen we het volgende zeggen:
> **Besturings systeem/platform:** ChromeOS wordt buitenschool het meest gebruikt onder de leerlingen. Het was vanaf het begin al het idee om een browser applicatie te maken, maar dit versterkt dat nog even. Mensen die geen ChromeOS gebruiken, gebruiken in de eerste plek Windows. Daarna komt Android en daarna iOS. We zullen in deze volgorde ondersteuning voor de platformen verlenen.

> **Kleurenschema:** De leerlingen zien het liefst de kleuren van het Greijdanus terug in de chat. Ook hebben ze liever een licht design dan een donker design, hoewel deze twee redelijk gelijk op gaan. Een kleurrijk ontwerp is niet erg geliefd. Wij gaan dan ook voor de Greijdanus-stijl, die van zichzelf al licht is.

>**App:** 118 van de leerlingen zegt dat ze wel een mobiele app zouden willen installeren, tegenover 83 respondenten die zeggen dat niet te willen doen. Het maken van een Android en/of een IOS applicatie lijkt ons het dan ook waard.

>**Gebruiksvriendlijkheid vs. opties:** Aan de leraren hebben we op een schaal van 1 tot 5 gevraagd of ze de nadruk willen hebben op de gebruiksvriendelijkheid of op meer opties. Het resultaat was als volgt:
>
>_Veel opties_
1. 0
2. 0
3. 6
4. 3
5. 6
>_Gebruiksvriendelijkheid_
>
>De nadruk ligt dus op gebruiksvriendelijkheid.

>**In de realiteit brengen?** De leerlingen zijn over het algemeen positief over een Greijdanus-chat, met maar 44 van de 240 die zeggen dat ze de chat niet zouden gebruiken. De leraren zijn minder positief, ze vermelden onder andere dat er al genoeg andere manieren zijn om te communiceren, zoals Whatsapp en Natschool mail, en dat ze liever niet 24/7 bereikbaar willen zijn. 9 van de 15 leraren zou zo'n chat niet (willen) gebruiken. Het lijkt ons dan ook niet verstandig om te proberen deze chat in de praktijk te brengen, aangezien er bij de leraren weinig support voor is.

>**Extra functies:** Suggesties van leerlingen: 

- [ ] roosters
- [ ] cijfers
- [ ] absenties bekijken
- [ ] (google) documenten en foto's dele
- [ ]  zoekfunctie naar leraren/leerlingen en contactgegevens weergeven
- [ ] meldingen bij berichten en roosterwijzigingen
- [ ] planning kunnen maken (voor toetsweek bijvoorbeeld)
- [ ] klassen/clusters bekijken
- [ ] tussenuur matcher (waarmee je kunt zien wie er nog meer tussenuur heeft
- [ ] huiswerkagenda
- [ ] van andere leerlingen en leraren de roosters kunnen bekijken
- [ ] (video)bellen
>Ze zien dus het liefst de functies terug die al bestaan in andere applicaties van het Greijdanus. Wij weten nog niet of we dit gaan proberen.

**Comment by nielsbergwerff** [comment]
> We hebben met onze opdrachtgever (het Greijdanus) overlegd wat de precieze vereisten zijn door middel van enquêtes.
> [De reacties van de leerlingen](https://docs.google.com/spreadsheets/d/1nQmR_XPLPr2jpHsTVJQdy1kXZJK2JgKRdBVk0K2Nm6E/edit#gid=1521884354)
> [De reacties van de leraren](https://docs.google.com/spreadsheets/d/1YwHd5QG_PMJzstk4sFXMfCvnJpy97E7CJziR_uop7BY/edit#gid=2001306950)

> 
> Hierdoor kunnen we het volgende zeggen:
> **Besturings systeem/platform:** ChromeOS wordt buitenschool het meest gebruikt onder de leerlingen. Het was vanaf het begin al het idee om een browser applicatie te maken, maar dit versterkt dat nog even. Mensen die geen ChromeOS gebruiken, gebruiken in de eerste plek Windows. Daarna komt Android en daarna iOS. We zullen in deze volgorde ondersteuning voor de platformen verlenen.

> **Kleurenschema:** De leerlingen zien het liefst de kleuren van het Greijdanus terug in de chat. Ook hebben ze liever een licht design dan een donker design, hoewel deze twee redelijk gelijk op gaan. Een kleurrijk ontwerp is niet erg geliefd. Wij gaan dan ook voor de Greijdanus-stijl, die van zichzelf al licht is.

>**App:** 118 van de leerlingen zegt dat ze wel een mobiele app zouden willen installeren, tegenover 83 respondenten die zeggen dat niet te willen doen. Het maken van een Android en/of een IOS applicatie lijkt ons het dan ook waard.

>**Gebruiksvriendlijkheid vs. opties:** Aan de leraren hebben we op een schaal van 1 tot 5 gevraagd of ze de nadruk willen hebben op de gebruiksvriendelijkheid of op meer opties. Het resultaat was als volgt:
>
>_Veel opties_
1. 0
2. 0
3. 6
4. 3
5. 6
>_Gebruiksvriendelijkheid_
>
>De nadruk ligt dus op gebruiksvriendelijkheid.

>**In de realiteit brengen?** De leerlingen zijn over het algemeen positief over een Greijdanus-chat, met maar 44 van de 240 die zeggen dat ze de chat niet zouden gebruiken. De leraren zijn minder positief, ze vermelden onder andere dat er al genoeg andere manieren zijn om te communiceren, zoals Whatsapp en Natschool mail, en dat ze liever niet 24/7 bereikbaar willen zijn. 9 van de 15 leraren zou zo'n chat niet (willen) gebruiken. Het lijkt ons dan ook niet verstandig om te proberen deze chat in de praktijk te brengen, aangezien er bij de leraren weinig support voor is.

>**Extra functies:** Suggesties van leerlingen: 

- [ ] roosters
- [ ] cijfers
- [ ] absenties bekijken
- [ ] (google) documenten en foto's dele
- [ ]  zoekfunctie naar leraren/leerlingen en contactgegevens weergeven
- [ ] meldingen bij berichten en roosterwijzigingen
- [ ] planning kunnen maken (voor toetsweek bijvoorbeeld)
- [ ] klassen/clusters bekijken
- [ ] tussenuur matcher (waarmee je kunt zien wie er nog meer tussenuur heeft
- [ ] huiswerkagenda
- [ ] van andere leerlingen en leraren de roosters kunnen bekijken
- [ ] (video)bellen
>Ze zien dus het liefst de functies terug die al bestaan in andere applicaties van het Greijdanus. Wij weten nog niet of we dit gaan proberen.
